# Generated by Django 3.0.4 on 2020-06-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaRecords', '0005_auto_20200415_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
